site:
  title: Frosthaven Enhanced
content:
  sources:
    - url: https://github.com/gloomhaven-tts-enhanced/public-scripts
      branches:
        - HEAD
        - next
      start_paths:
        - docs/content/*
    - url: https://github.com/gloomhaven-tts-enhanced/public-scripts
      branches: maintain/1.3
      start_paths:
        - docs/content/*
        - "!docs/content/development"
urls:
  latest_version_segment: latest
  latest_prerelease_version_segment: next
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./ui
antora:
  extensions:
    - require: "@antora/lunr-extension"
      index_latest_only: true
      snippet_length: 200
asciidoc:
  attributes:
    experimental: true
